from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator


class AgentToolCall(BaseModel):
    """A single planned tool call generated by the planner."""

    tool_name: str = Field(..., min_length=1)
    reason: str = Field(default="")
    input: dict[str, Any] = Field(default_factory=dict)

    @field_validator("tool_name", mode="before")
    @classmethod
    def normalize_tool_name(cls, value):
        return str(value or "").strip()


class AgentPlan(BaseModel):
    """Structured plan for a production-style agent run."""

    intent: str = Field(default="follow_up_qa")
    goal: str = Field(default="回答用户关于简历与岗位匹配的问题。")
    steps: list[AgentToolCall] = Field(default_factory=list, max_length=8)
    final_response_style: Literal["actionable", "interview", "resume_bullets", "diagnostic"] = "actionable"
    requires_human_review: bool = False

    @field_validator("intent", mode="before")
    @classmethod
    def normalize_intent(cls, value):
        return str(value or "follow_up_qa").strip() or "follow_up_qa"

    @model_validator(mode="after")
    def ensure_steps(self):
        if not self.steps:
            self.steps = [
                AgentToolCall(
                    tool_name="extract_job_keywords",
                    reason="先提取岗位关键词，作为后续分析基础。",
                    input={},
                ),
                AgentToolCall(
                    tool_name="analyze_keyword_gap",
                    reason="比较简历与岗位关键词，识别能力缺口。",
                    input={},
                ),
                AgentToolCall(
                    tool_name="generate_final_answer",
                    reason="汇总工具结果，生成最终回答。",
                    input={},
                ),
            ]
        return self


class AgentTraceStep(BaseModel):
    """Execution trace for one tool call."""

    step_id: int
    tool_name: str
    reason: str = ""
    input: dict[str, Any] = Field(default_factory=dict)
    output: Any = None
    status: Literal["success", "failed", "skipped"] = "success"
    error: str | None = None


class AgentRunOutput(BaseModel):
    """Public response for the agent endpoint."""

    intent: str
    final_answer: str
    plan: dict[str, Any] = Field(default_factory=dict)
    steps: list[dict[str, Any]] = Field(default_factory=list)
    result: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.7, ge=0, le=1)
    mode: Literal["llm_planner", "rule_fallback"] = "rule_fallback"
    warnings: list[str] = Field(default_factory=list)
